version: '3.5'

services:
  ant-design-pro_dev:
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: 'ant-design-pro_dev'
    volumes:
      - ../src:/usr/src/pages/src
      - ../config:/usr/src/pages/config
      - ../mock:/usr/src/pages/mock
